
# This config file is for use with the `build_data` and `check_data` functions,
# which are helpers for implementations of Open SDG. This file allows easy use
# of those functions without altering Python code.

# The following should be changed according to the hosting environment. In the most
# common environment, Github Pages, you would need to set this according to the name
# of this repository, after a preceding slash. Eg: /my-repository-name
docs_baseurl: /open-sdg-simple-starter

# Languages
# ---------
# This tells sdg-build to perform "translated builds" for each of the specified
# languages. Each build is in its own subfolder - one for each language.
languages:
  - en

# Destination directory
# ---------------------
# This identifies a directory to hold the "built" files. The default is '_site'.
# Here we use '_build' to avoid conflicting with Jekyll, which uses '_site'.
site_dir: _build

# Schema file
# -----------
# This identifies a file containing the schema (possible fields) for metadata.
# Currently this needs to be a prose.io config, and defaults to '_prose.yml'.
schema_file: _prose.yml

# Source directory
# ----------------
# This identifies the directory that holds the 'data' and 'meta' folders.
# The default, '', points to the root of this repository.
src_dir: ''

# Inputs
# ------
# The allows control over the inputs of data and metadata. This can be omitted
# if you are using the standard Open SDG approach of CSV data and YAML metadata.
# But if you would like to use non-standard inputs (such as SDMX) then you can
# use this as needed.
#
# Each item must have a "class" which corresponds to classes in the sdg/inputs
# folder. Further, each item can have any/all of the parameters that class uses.
# The defaults below show what is used when this is omitted.
inputs:
  - class: InputPxWebApi
    # This describes the data files, relative to the "src_dir" indicated above.
    endpoint: http://jorinfo.dos.gov.jo/Databank/api/v1/en/SDG/
    post_data:
      query: []
    year_column: Time
    value_column: value
    sleep: 5
    indicator_id_map:
      GOL01/Target01/111.px: 1-1-1
      GOL01/Target02/121.px: 1-2-1
      GOL01/Target05/151.px: 1-5-1
      GOL01/Target05/152.px: 1-5-2
      GOL01/Target05/153.px: 1-5-3
      GOL01/Target05/154.px: 1-5-4
      GOL01/Target09/162.px: 1-6-2
      GOL04/Target1/411.px: 4-1-1
      GOL04/Target1/412.px: 4-1-2
      GOL04/Target1/413.px: 4-1-3
      GOL04/Target1/414.px: 4-1-4
      GOL04/Target1/415.px: 4-1-5
      GOL04/Target1/416.px: 4-1-6
      GOL04/Target2/421.px: 4-2-1
      GOL04/Target2/422.px: 4-2-2
      GOL04/Target3/431.px: 4-3-1
      GOL04/Target3/433.px: 4-3-3
      GOL04/Target4/441.px: 4-4-1
      GOL04/Target5/451.px: 4-5-1
      GOL04/Target5/452.px: 4-5-2
      GOL04/Target6/461.px: 4-6-1
      GOL04/Target7/471.px: 4-7-1
      GOL05/Target1/511.px: 5-1-1
      GOL05/Target2/521.px: 5-2-1
      GOL05/Target3/531.px: 5-3-1
      GOL05/Target5/551.px: 5-5-1
      GOL05/Target5/5521.px: 5-5-21
      GOL05/Target6/651.px: 6-5-1
      GOL05/Target7/571.px: 5-7-1
      GOL05/Target8/581.px: 5-8-1
      GOL06/Target1/611.px: 6-1-1
      GOL06/Target2/621.px: 6-2-1
      GOL06/Target3/631.px: 6-3-1
      GOL06/Target3/632.px: 6-3-2
      GOL06/Target4/641.px: 6-4-1
      GOL06/Target4/642.px: 6-4-2
      GOL06/Target5/651.px: 6-5-1
      GOL06/Target5/652.px: 6-5-2
      GOL06/Target7/671.px: 6-7-1
      GOL06/Target8/681.px: 6-8-1
      GOL09/Target1/912.px: 9-1-2
      GOL09/Target2/921.px: 9-2-1
      GOL09/Target2/922.px: 9-2-2
      GOL09/Target3/932.px: 9-3-2
      GOL09/Target4/941.px: 9-4-1
      GOL09/Target5/951.px: 9-5-1
      GOL09/Target5/952.px: 9-5-2
      GOL09/Target6/961.px: 9-6-1
      GOL09/Target7/971.px: 9-7-1
      GOL09/Target8/981.px: 9-8-1
      GOL11/Target01/1111a.px: 11-1-1a
      GOL11/Target06/1162.px: 11-6-2
      GOL11/Target07/11b1.px: 11-7-b1
      GOL11/Target07/11b2.px: 11-7-b2
      GOL12/Target01/1211.px: 12-1-1
      GOL12/Target04/1241.px: 12-4-1
      GOL12/Target05/1251.px: 12-5-1
      GOL16/Target02/1621.px: 16-2-1
      GOL16/Target02/1622.px: 16-2-2
      GOL16/Target03/1632.px: 16-3-2
      GOL16/Target05/1652.px: 16-5-2
      GOL16/Target06/1661.px: 16-6-1
      GOL17/Target01/1711.px: 17-1-1
      GOL17/Target01/1712.px: 17-1-2
      GOL17/Target10/17101.px: 17-10-1
      GOL17/Target13/17131.px: 17-13-1
      GOL17/Target18/17182.px: 17-18-2
      GOL17/Target19/17191.px: 17-19-1
      GOL17/Target03/1732.px: 17-3-2
      GOL17/Target04/1741.px: 17-4-1
      GOL17/Target06/1762.px: 17-6-2
      GOL17/Target08/1781.px: 17-8-1
      GOL17/Target09/1791.px: 17-9-1

# Translations
# ------------
# The allows control over the imported translations. This can be omitted if you
# are happy with the defaults. But if you are using custom translation repos
# or non-standard inputs (such as SDMX) then you can use this as needed.
#
# Each item must have a "class" which corresponds to classes in the sdg-build
# project. Further, each item can have any/all of the parameters that class uses.
# The defaults below show what is used when this is omitted.
translations:
  # This pulls in translations from a Git repository.
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: 1.3.1
  # This pulls in translations from a local 'translations' folder.
  - class: TranslationInputYaml
    source: translations

# Reporting status extra fields
# -----------------------------
# This allows the build to generate stats for reporting status by additional
# fields, beyond the default "status by goal" report.
reporting_status_extra_fields: []

# Map layers
# ----------
# This allows the build to generate one or more GeoJSON files to be used by
# Open SDG maps. The parameters available correspond to the OutputGeoJson class.
# See sdg/outputs/OutputGeoJson.py for more information. Uncomment the map_layers
# below and adjust if you would like to use the Open SDG mapping functionality.
# Note that the GeoJSON files can either be remote (as in the example below) or
# local, relative to the src_dir specified above.
#map_layers:
#  - geojson_file: https://geoportal1-ons.opendata.arcgis.com/datasets/4fcca2a47fed4bfaa1793015a18537ac_4.geojson
#    name_property: rgn17nm
#    id_property: rgn17cd
#    output_subfolder: regions
#    filename_prefix: indicator_

# Documentation settings
# ----------------------
# This controls the automatic documentation that is created for your build.
#
# This is the logo at the top of the automated documentation pages.
docs_branding: SDG data build documentation
# This displays at the top of the automated documentation homepage.
docs_intro: This is a list of examples of endpoints and output that are
  available on this service. Click each of the links below for more information
  on the available output.
docs_subfolder: data-docs
# This can be uncommented and updated so allow links to your indicator pages.
# The URL here should have [id] instead of the indicator ID.
#docs_indicator_url: https://my-github-org/my-site-repository/[id]
